# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pt3_comm.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0ept3_comm.proto\x12\rcommunication\"T\n\rArray_message\x12\x10\n\x08\x64\x61tatype\x18\x01 \x01(\t\x12\r\n\x05width\x18\x02 \x01(\x05\x12\x0e\n\x06height\x18\x03 \x01(\x05\x12\x12\n\nbytesarray\x18\x04 \x01(\x0c\"\x07\n\x05\x45mpty2\xe7\x01\n\x14\x43ommunication_Server\x12O\n\x17_send_and_display_image\x12\x1c.communication.Array_message\x1a\x14.communication.Empty\"\x00\x12?\n\x0f_display_points\x12\x14.communication.Empty\x1a\x14.communication.Empty\"\x00\x12=\n\r_display_dark\x12\x14.communication.Empty\x1a\x14.communication.Empty\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pt3_comm_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ARRAY_MESSAGE']._serialized_start=33
  _globals['_ARRAY_MESSAGE']._serialized_end=117
  _globals['_EMPTY']._serialized_start=119
  _globals['_EMPTY']._serialized_end=126
  _globals['_COMMUNICATION_SERVER']._serialized_start=129
  _globals['_COMMUNICATION_SERVER']._serialized_end=360
# @@protoc_insertion_point(module_scope)
